### PR TITLE
Added Goa parser

### PR DESCRIPTION
**Pull request by raghavio**

### CODE REVIEW

**Comment by anandology** [comment]
When I tried the search by voterid form on CEO Goa website, it didn't work when I selected seaech-with-district, but worked fine when I selected the AC. Could you check and confirm if search-with-district is working as expected.

**Comment by raghavio** [comment]
@anandology must be some bug. It's working now. Try TRW0116020 in North Goa

**Comment by anandology** [comment]
Yep. working for me too.

Anand

**Comment by anandology** [comment]
Thanks @RaghavPro. deployed!

**Pull request merged**
